/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.gradely.client.gui.settings;

/**
 * This class represents the bottom button in the SettingsDialog that saves the right-side JPanels form information.
 * @author Matt
 */
public class BottomButtons extends javax.swing.JPanel {

    /**
     * If isSaved is false, then the panel will say "Saved"
     */
    private boolean isSaved = false; 

    /**
     * @return the isSaved
     */
    public boolean getIsSaved() {
        return isSaved;
    }

    /**
     * @param aIsSaved the isSaved to set
     */
    public void setIsSaved(boolean aIsSaved) {
        
        if(aIsSaved == true)
        {
            jLabel1.setText("Saved");
            jLabel1.revalidate();
            jLabel1.repaint();
        }
        else
        {
            jLabel1.setText("");
            jLabel1.revalidate();
            jLabel1.repaint();
        }
        
        isSaved = aIsSaved;
    }
    
    /**
     * Creates new form BottomButtons
     */
    public BottomButtons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(363, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Save the Right Side
        SettingsDialog.getRight().saveForms();
        
        //Set jLabel1 to say "Saved" in order to inform the user
        jLabel1.setText("Saved");
        jLabel1.revalidate();
        jLabel1.repaint();
        
        isSaved = true;
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
