/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.gradely.client.gui;

import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import org.gradely.client.SHA2Hashsum;
import org.gradely.client.config.Configuration;
import org.gradely.client.logging.Logging;

/**
 *
 * @author Matt
 */
public class UserPanel extends PanelAbstractClass {

    /**
     * From PanelAbstractClass. Loads values into forms.
     */
    @Override
    public void loadForms()
    {
        Configuration c = org.gradely.client.config.Configuration.getInstance(); 
        jTextField1.setText(c.getServerName());
        jTextField1.setText(c.getUsername());
    }
    
    /**
     * From PanelAbstractClass. Saves values from forms.
     */
    @Override
    public void saveForms() throws NoSuchAlgorithmException, UnsupportedEncodingException
    {
        Configuration c = org.gradely.client.config.Configuration.getInstance(); 
       
        //Password
        char[] passwordArr = jPasswordField2.getPassword();
        StringBuilder sb = new StringBuilder();
        sb.append(passwordArr);
        String password = sb.toString();
        password = password.trim();
        
        if(org.apache.commons.lang3.StringUtils.isNotBlank(password))
        {
            try
            {
                byte[] hashPassArr = SHA2Hashsum.computeHash(password);
                String hashPass = SHA2Hashsum.bytesToHex(hashPassArr);

                if(hashPass == null ? c.getPasswordHash() != null : !hashPass.equals(c.getPasswordHash()))
                {
                    c.setPasswordHash(hashPass);
                }
            }
            catch(NoSuchAlgorithmException |UnsupportedEncodingException e)
            {
                Logging.warning("Cannot compute the hash of the password.", e);
                throw e;
            }
        }
        
        //Username
        String username = jTextField2.getText();
        if (username == null ? c.getUsername() == null : !username.equals(c.getUsername()))
        {
            c.setUsername(username);
        }
        
        //Domain name
        String domain = jTextField1.getText();
        if (domain == null ? c.getServerName() == null : !domain.equals(c.getServerName()))
        {
            c.setServerName(domain);
        }
        
        try
        {
            c.save();
        }
        catch(IOException e)
        {
            Logging.warning("Cannot save the configuration", e);
        }
        
        
    }
    
    /**
     * Creates new form UserPanel
     */
    public UserPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();

        jLabel1.setText("Server Domain Name");

        jLabel2.setText("Username");

        jTextField1.setText(org.gradely.client.config.Configuration.getInstance().getServerName());

        jTextField2.setText(org.gradely.client.config.Configuration.getInstance().getUsername());

        jLabel3.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField2)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(186, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
